language: generic
sudo: required
services:
        - docker

before_install:
        - docker image build -t enigma777/ops-web-demo:test -f Dockerfile.dev .

script:
        - docker container run -e CI=true enigma777/ops-web-demo:test yarn test
